(define (zqug-mk)
  (list nil))
(define (zqug-set-rect! gob x y w h)
  (set-car! gob (list x y w h)))
(define (zqug-get-rect gob) 
  (car gob))

(kern-ztats-add-pane
 (lambda (gob kparty dir x y w h)
   (println "enter")
   (kern-ztats-set-title "Quest Log")
   (zqug-set-rect! gob x y w h)
   )
 (lambda (gob dir)
   (println "scroll")
   #f)
 (lambda (gob)
   (println "paint:" gob)
   (let ((dims (zqug-get-rect gob)))
     (println dims)
     (kern-screen-print (car dims) (cadr dims) (caddr dims) (cadddr dims)
                        0
                        "No Quests!")))
 (zqug-mk))
