#!/bin/sh

for test in `cat list`; do
  printf $test
  cd ..
  nazghul --playback tests/$test.rec --playback_speed 0 tests/$test.scm 2> tests/$test.err > tests/$test.out
  mv save.scm tests/$test.save
  cd tests
  diff $test.save $test.save.mstr > $test.diff
  if [ $? != 0 ]; then
    printf " FAIL\n"
  else
    printf " PASS\n"
  fi
done