;; mk-scenery-type is rather like mk-reagent-type, 
;; but on the terrain features layer, and without an interface.
;; 
;; In future, it will be needful to have some kind of interface --
;; it is an explicit goal in Haxima to enable the player to interact with 
;; the world (and its' objects) whenever reasonable.
(define (mk-scenery-type tag name sprite)
  (mk-obj-type tag name sprite layer-tfeat nil))

;; Lightning bolts:
(mk-scenery-type 't_lightning_bolt_red        "lightning bolt" s_lightning_bolt_red)
(mk-scenery-type 't_lightning_bolt_green      "lightning bolt" s_lightning_bolt_green)
(mk-scenery-type 't_lightning_bolt_blue       "lightning bolt" s_lightning_bolt_blue)
(mk-scenery-type 't_lightning_bolt_cyan       "lightning bolt" s_lightning_bolt_cyan)
(mk-scenery-type 't_lightning_bolt_purple     "lightning bolt" s_lightning_bolt_purple)
(mk-scenery-type 't_lightning_bolt_yellow     "lightning bolt" s_lightning_bolt_yellow)
(mk-scenery-type 't_lightning_bolt_brown      "lightning bolt" s_lightning_bolt_brown)
(mk-scenery-type 't_lightning_bolt_orange     "lightning bolt" s_lightning_bolt_orange)
(mk-scenery-type 't_lightning_bolt_white      "lightning bolt" s_lightning_bolt_white)
(mk-scenery-type 't_lightning_bolt_grey       "lightning bolt" s_lightning_bolt_grey)
(mk-scenery-type 't_lightning_bolt_dark_grey  "lightning bolt" s_lightning_bolt_dark_grey)
(mk-scenery-type 't_lightning_bolt_chromatic  "lightning bolt" s_lightning_bolt_chromatic)
;; Magic ball (fireball core or similar):
(mk-scenery-type 't_fireball_red        "fireball" s_magic_ball_core_red)
(mk-scenery-type 't_fireball_green      "fireball" s_magic_ball_core_green)
(mk-scenery-type 't_fireball_blue       "fireball" s_magic_ball_core_blue)
(mk-scenery-type 't_fireball_cyan       "fireball" s_magic_ball_core_cyan)
(mk-scenery-type 't_fireball_purple     "fireball" s_magic_ball_core_purple)
(mk-scenery-type 't_fireball_yellow     "fireball" s_magic_ball_core_yellow)
(mk-scenery-type 't_fireball_brown      "fireball" s_magic_ball_core_brown)
(mk-scenery-type 't_fireball_orange     "fireball" s_magic_ball_core_orange)
(mk-scenery-type 't_fireball_white      "fireball" s_magic_ball_core_white)
(mk-scenery-type 't_fireball_grey       "fireball" s_magic_ball_core_grey)
(mk-scenery-type 't_fireball_dark_grey  "fireball" s_magic_ball_core_dark_grey)
(mk-scenery-type 't_fireball_chromatic  "fireball" s_magic_ball_core_chromatic)
;; Magic burst/bloom/aura/field (5 ball lightnings in one tile):
(mk-scenery-type 't_magic_field_red           "magic field" s_magic_field_red)
(mk-scenery-type 't_magic_field_green         "magic field" s_magic_field_green)
(mk-scenery-type 't_magic_field_blue          "magic field" s_magic_field_blue)
(mk-scenery-type 't_magic_field_cyan          "magic field" s_magic_field_cyan)
(mk-scenery-type 't_magic_field_purple        "magic field" s_magic_field_purple)
(mk-scenery-type 't_magic_field_yellow        "magic field" s_magic_field_yellow)
(mk-scenery-type 't_magic_field_brown         "magic field" s_magic_field_brown)
(mk-scenery-type 't_magic_field_orange        "magic field" s_magic_field_orange)
(mk-scenery-type 't_magic_field_white         "magic field" s_magic_field_white)
(mk-scenery-type 't_magic_field_grey          "magic field" s_magic_field_grey)
(mk-scenery-type 't_magic_field_dark_grey     "magic field" s_magic_field_dark_grey)
(mk-scenery-type 't_magic_field_blue_2        "magic field" s_magic_field_blue_2)
(mk-scenery-type 't_magic_field_red_pulsed    "pulsing magic field" s_magic_field_red_pulsed)
(mk-scenery-type 't_magic_field_green_pulsed  "pulsing magic field" s_magic_field_green_pulsed)
(mk-scenery-type 't_magic_field_blue_pulsed   "pulsing magic field" s_magic_field_blue_pulsed)
(mk-scenery-type 't_magic_field_white_pulsed  "pulsing magic field" s_magic_field_white_pulsed)
(mk-scenery-type 't_magic_field_purple_pulsed "pulsing magic field" s_magic_field_purple_pulsed)
(mk-scenery-type 't_magic_field_brown_pulsed  "pulsing magic field" s_magic_field_brown_pulsed)
(mk-scenery-type 't_magic_field_blue_2_pulsed "pulsing magic field" s_magic_field_blue_2_pulsed)
;; Chromatic ball lightning (8 frames):
(mk-scenery-type 't_magic_field_chromatic_pulsed "pulsing magic field" s_magic_field_chromatic_pulsed)
;; Lightning discharges:
(mk-scenery-type 't_lightning_discharge_red   "lightning" s_lightning_discharge_red)
(mk-scenery-type 't_lightning_discharge_green "lightning" s_lightning_discharge_green)
(mk-scenery-type 't_lightning_discharge_blue  "lightning" s_lightning_discharge_blue)
(mk-scenery-type 't_lightning_discharge_black "lightning" s_lightning_discharge_black)
;; Lightning discharges in cloud:
(mk-scenery-type 't_lightning_cloud_red    "lightning cloud" s_lightning_cloud_blue_red)
(mk-scenery-type 't_lightning_cloud_green  "lightning cloud" s_lightning_cloud_blue_green)
(mk-scenery-type 't_lightning_cloud_blue   "lightning cloud" s_lightning_cloud_blue_blue)
(mk-scenery-type 't_lightning_cloud_purple "lightning cloud" s_lightning_cloud_blue_purple)
(mk-scenery-type 't_lightning_cloud_yellow "lightning cloud" s_lightning_cloud_blue_yellow)
(mk-scenery-type 't_lightning_cloud_orange "lightning cloud" s_lightning_cloud_blue_orange)
;; Magical spheres:
(mk-scenery-type 't_magic_sphere_red    "magical sphere" s_magic_sphere_red)
(mk-scenery-type 't_magic_sphere_green  "magical sphere" s_magic_sphere_green)
(mk-scenery-type 't_magic_sphere_blue   "magical sphere" s_magic_sphere_blue)
(mk-scenery-type 't_magic_sphere_yellow "magical sphere" s_magic_sphere_yellow)
(mk-scenery-type 't_magic_sphere_purple "magical sphere" s_magic_sphere_purple)
(mk-scenery-type 't_magic_sphere_cyan   "magical sphere" s_magic_sphere_cyan)
;; Magical spheres with light rays:
(mk-scenery-type 't_magic_sphere_rays_red    "magical sphere" s_magic_sphere_rays_red)
(mk-scenery-type 't_magic_sphere_rays_green  "magical sphere" s_magic_sphere_rays_green)
(mk-scenery-type 't_magic_sphere_rays_blue   "magical sphere" s_magic_sphere_rays_blue)
(mk-scenery-type 't_magic_sphere_rays_yellow "magical sphere" s_magic_sphere_rays_yellow)
(mk-scenery-type 't_magic_sphere_rays_purple "magical sphere" s_magic_sphere_rays_purple)
(mk-scenery-type 't_magic_sphere_rays_cyan   "magical sphere" s_magic_sphere_rays_cyan)
;; Arrows and Bolts and such in flight:
(mk-scenery-type 't_arrow_wood_red    "arrow" s_arrow_wood_red)
(mk-scenery-type 't_arrow_metal_red   "arrow" s_arrow_metal_red)
(mk-scenery-type 't_arrow_wood_green  "arrow" s_arrow_wood_green)
(mk-scenery-type 't_arrow_metal_green "arrow" s_arrow_metal_green)
