;;----------------------------------------------------------------------------
;; Sprites
;;----------------------------------------------------------------------------
;; 's_some_sprite ss_some_sprite_set num_tiles tile_number wave_sprite facing_value
;; 
;; facing_value is the sum of all facings provided by this sprite.
;; The value is determined by adding:
;;    1 NorthWest
;;    2 North
;;    4 NorthEast
;;    8 West
;;   16 Here
;;   32 East
;;   64 SouthWest
;;  128 South
;;  256 SouthEast
;;  512 Up
;; 1024 Down
;; 
;; Common values include:
;;   0 Default facing (only 1 facing, used for all directions)
;;  40 WE facing
;; 170 NSEW facing
;;----------------------------------------------------------------------------

(kern-mk-sprite 's_deep ss_u4 1 0 #t 0 )
(kern-mk-sprite 's_shallow ss_u4 1 1 #t 0 )
(kern-mk-sprite 's_shoals ss_u4 1 2 #t 0 )
(kern-mk-sprite 's_bog ss_u4 1 3 #t 0 )
(kern-mk-sprite 's_grass ss_u4 1 4 #f 0 )
(kern-mk-sprite 's_trees ss_u4 1 5 #f 0 )
(kern-mk-sprite 's_forest ss_u4 1 6 #f 0 )
(kern-mk-sprite 's_hills ss_u4 1 7 #f 0 )
(kern-mk-sprite 's_mountains ss_u4 1 8 #f 0 )
(kern-mk-sprite 's_dungeon ss_u4 1 9 #f 0 )
(kern-mk-sprite 's_town ss_u4 1 10 #f 0 )
(kern-mk-sprite 's_keep ss_u4 1 11 #f 0 )
(kern-mk-sprite 's_hamlet ss_u4 1 12 #f 0 )
(kern-mk-sprite 's_leftwing ss_u4 1 13 #f 0 )
(kern-mk-sprite 's_castle ss_u4 1 14 #f 0 )
(kern-mk-sprite 's_rightwing ss_u4 1 15 #f 0 )
(kern-mk-sprite 's_cobblestone ss_u4 1 22 #f 0 )
(kern-mk-sprite 's_bridge ss_u4 1 23 #f 0 )
(kern-mk-sprite 's_ballon ss_u4 1 24 #f 0 )
(kern-mk-sprite 's_bridge_top ss_u4 1 25 #f 0 )
(kern-mk-sprite 's_bridge_bottom ss_u4 1 26 #f 0 )
(kern-mk-sprite 's_ladder_up ss_u4 1 27 #f 0 )
(kern-mk-sprite 's_ladder_down ss_u4 1 28 #f 0 )
(kern-mk-sprite 's_ruin ss_u4 1 29 #f 0 )
(kern-mk-sprite 's_shrine ss_u4 1 30 #f 0 )
(kern-mk-sprite 's_avatar ss_u4 1 31 #f 0 )
(kern-mk-sprite 's_companion_wizard ss_u4 2 32 #f 0 )
(kern-mk-sprite 's_companion_bard ss_u4 2 34 #f 0 )
(kern-mk-sprite 's_companion_fighter ss_u4 2 36 #f 0 )
(kern-mk-sprite 's_companion_druid ss_u4 2 38 #f 0 )
(kern-mk-sprite 's_companion_tinker ss_u4 2 40 #f 0 )
(kern-mk-sprite 's_companion_paladin ss_u4 2 42 #f 0 )
(kern-mk-sprite 's_companion_ranger ss_u4 2 44 #f 0 )
(kern-mk-sprite 's_companion_shepherd ss_u4 2 46 #f 0 )
(kern-mk-sprite 's_pillar ss_u4 1 48 #f 0 )
(kern-mk-sprite 's_wall_b ss_u4 1 49 #f 0 )
(kern-mk-sprite 's_wall_a ss_u4 1 50 #f 0 )
(kern-mk-sprite 's_wall_c ss_u4 1 51 #f 0 )
(kern-mk-sprite 's_wall_d ss_u4 1 52 #f 0 )
(kern-mk-sprite 's_mast ss_u4 1 53 #f 0 )
(kern-mk-sprite 's_ships_wheel ss_u4 1 54 #f 0 )
(kern-mk-sprite 's_boulder ss_u4 1 55 #f 0 )
(kern-mk-sprite 's_corpse ss_u4 1 56 #f 0 )
(kern-mk-sprite 's_wall_rock ss_u4 1 57 #f 0 )
(kern-mk-sprite 's_door_locked ss_u4 1 58 #f 0 )
(kern-mk-sprite 's_door ss_u4 1 59 #f 0 )
(kern-mk-sprite 's_chest ss_u4 1 60 #f 0 )
(kern-mk-sprite 's_ankh ss_u4 1 61 #f 0 )
(kern-mk-sprite 's_flagstone ss_u4 1 62 #f 0 )
(kern-mk-sprite 's_deck ss_u4 1 63 #f 0 )
(kern-mk-sprite 's_moongate_quarter ss_u4 1 64 #f 0 )
(kern-mk-sprite 's_moongate_half ss_u4 1 65 #f 0 )
(kern-mk-sprite 's_moongate_three_quarters ss_u4 1 66 #f 0 )
(kern-mk-sprite 's_moongate_full ss_u4 1 67 #f 0 )
(kern-mk-sprite 's_field_poison ss_u4 1 68 #t 0 )
(kern-mk-sprite 's_field_energy ss_u4 1 69 #t 0 )
(kern-mk-sprite 's_field_fire ss_u4 1 70 #t 0 )
(kern-mk-sprite 's_field_sleep ss_u4 1 71 #t 0 )
(kern-mk-sprite 's_wall ss_u4 1 72 #f 0 )
(kern-mk-sprite 's_secret_door ss_u4 1 73 #f 0 )
(kern-mk-sprite 's_altar ss_u4 1 74 #f 0 )
(kern-mk-sprite 's_lava ss_u4 1 76 #t 0 )
(kern-mk-sprite 's_projectile ss_u4 1 77 #f 0 )
(kern-mk-sprite 's_magic ss_u4 1 78 #f 0 )
(kern-mk-sprite 's_hit ss_u4 1 79 #f 0 )
(kern-mk-sprite 's_guard ss_u4 2 80 #f 0 )
(kern-mk-sprite 's_townsman ss_u4 2 82 #f 0 )
(kern-mk-sprite 's_bard ss_u4 2 84 #f 0 )
(kern-mk-sprite 's_jester ss_u4 2 86 #f 0 )
(kern-mk-sprite 's_beggar ss_u4 2 88 #f 0 )
(kern-mk-sprite 's_child ss_u4 2 90 #f 0 )
(kern-mk-sprite 's_bull ss_u4 2 92 #f 0 )
(kern-mk-sprite 's_aristocrat ss_u4 2 94 #f 0 )
(kern-mk-sprite 's_A ss_u4 1 96 #f 0 )
(kern-mk-sprite 's_B ss_u4 1 97 #f 0 )
(kern-mk-sprite 's_C ss_u4 1 98 #f 0 )
(kern-mk-sprite 's_D ss_u4 1 99 #f 0 )
(kern-mk-sprite 's_E ss_u4 1 100 #f 0 )
(kern-mk-sprite 's_F ss_u4 1 101 #f 0 )
(kern-mk-sprite 's_G ss_u4 1 102 #f 0 )
(kern-mk-sprite 's_H ss_u4 1 103 #f 0 )
(kern-mk-sprite 's_I ss_u4 1 104 #f 0 )
(kern-mk-sprite 's_J ss_u4 1 105 #f 0 )
(kern-mk-sprite 's_K ss_u4 1 106 #f 0 )
(kern-mk-sprite 's_L ss_u4 1 107 #f 0 )
(kern-mk-sprite 's_M ss_u4 1 108 #f 0 )
(kern-mk-sprite 's_N ss_u4 1 109 #f 0 )
(kern-mk-sprite 's_O ss_u4 1 110 #f 0 )
(kern-mk-sprite 's_P ss_u4 1 111 #f 0 )
(kern-mk-sprite 's_Q ss_u4 1 112 #f 0 )
(kern-mk-sprite 's_R ss_u4 1 113 #f 0 )
(kern-mk-sprite 's_S ss_u4 1 114 #f 0 )
(kern-mk-sprite 's_T ss_u4 1 115 #f 0 )
(kern-mk-sprite 's_U ss_u4 1 116 #f 0 )
(kern-mk-sprite 's_V ss_u4 1 117 #f 0 )
(kern-mk-sprite 's_W ss_u4 1 118 #f 0 )
(kern-mk-sprite 's_X ss_u4 1 119 #f 0 )
(kern-mk-sprite 's_Y ss_u4 1 120 #f 0 )
(kern-mk-sprite 's_Z ss_u4 1 121 #f 0 )
(kern-mk-sprite 's_counter_middle ss_u4 1 122 #f 0 )
(kern-mk-sprite 's_counter_right ss_u4 1 123 #f 0 )
(kern-mk-sprite 's_counter_left ss_u4 1 124 #f 0 )
(kern-mk-sprite 's_counter_1x1 ss_u4 1 125 #f 0 )
(kern-mk-sprite 's_blank ss_u4 1 126 #f 0 )
(kern-mk-sprite 's_null ss_u4 1 126 #f 0 )
(kern-mk-sprite 's_wall_stone ss_u4 1 127 #f 0 )
(kern-mk-sprite 's_pirate_left ss_u4 1 128 #f 0 )
(kern-mk-sprite 's_pirate_front ss_u4 1 129 #f 0 )
(kern-mk-sprite 's_pirate_right ss_u4 1 130 #f 0 )
(kern-mk-sprite 's_pirate_back ss_u4 1 131 #f 0 )
(kern-mk-sprite 's_nixie ss_u4 2 132 #f 0 )
(kern-mk-sprite 's_kraken ss_u4 2 134 #f 0 )
(kern-mk-sprite 's_sea_serpent ss_u4 2 136 #f 0 )
(kern-mk-sprite 's_sea_horse ss_u4 2 138 #f 0 )
(kern-mk-sprite 's_whirlpool ss_u4 2 140 #f 0 )
(kern-mk-sprite 's_tornado ss_u4 2 142 #f 0 )
(kern-mk-sprite 's_rat ss_u4 4 144 #f 0 )
(kern-mk-sprite 's_bat ss_u4 4 148 #f 0 )
(kern-mk-sprite 's_spider ss_u4 4 152 #f 0 )
(kern-mk-sprite 's_ghost ss_u4 4 156 #f 0 )
(kern-mk-sprite 's_slime ss_u4 4 160 #f 0 )
(kern-mk-sprite 's_slime_asleep ss_u4 1 160 #f 0 )
(kern-mk-sprite 's_shaman ss_u4 4 164 #f 0 )
(kern-mk-sprite 's_gemlin ss_u4 4 168 #f 0 )
(kern-mk-sprite 's_mimic ss_u4 4 172 #f 0 )
(kern-mk-sprite 's_reaper ss_u4 4 176 #f 0 )
(kern-mk-sprite 's_insects ss_u4 4 180 #f 0 )
(kern-mk-sprite 's_gazer ss_u4 4 184 #f 0 )
(kern-mk-sprite 's_knight ss_u4 4 188 #f 0 )
(kern-mk-sprite 's_orc ss_u4 4 192 #f 0 )
(kern-mk-sprite 's_skeleton ss_u4 4 196 #f 0 )
(kern-mk-sprite 's_brigand ss_u4 4 200 #f 0 )
(kern-mk-sprite 's_snake ss_u4 4 204 #f 0 )
(kern-mk-sprite 's_etin ss_u4 4 208 #f 0 )
(kern-mk-sprite 's_headless ss_u4 4 212 #f 0 )
(kern-mk-sprite 's_cyclops ss_u4 4 216 #f 0 )
(kern-mk-sprite 's_wisp ss_u4 4 220 #f 0 )
(kern-mk-sprite 's_wizard ss_u4 4 224 #f 0 )
(kern-mk-sprite 's_lich ss_u4 4 228 #f 0 )
(kern-mk-sprite 's_drake ss_u4 4 232 #f 0 )
(kern-mk-sprite 's_xorn ss_u4 4 236 #f 0 )
(kern-mk-sprite 's_demon ss_u4 4 240 #f 0 )
(kern-mk-sprite 's_hydra ss_u4 4 244 #f 0 )
(kern-mk-sprite 's_dragon ss_u4 4 248 #f 0 )
(kern-mk-sprite 's_balron ss_u4 4 252 #f 0 )


(kern-mk-sprite 's_crosshair ss_mine 1 0 #f 0)
(kern-mk-sprite 's_arrow  ss_mine 1 1 #f 170 )
(kern-mk-sprite 's_horse  ss_mine 1 5 #f 40 )
(kern-mk-sprite 's_happy_monster_face  ss_mine 1 7 #f 0 )
(kern-mk-sprite 's_ship  ss_mine 1 8 #f 170 )
(kern-mk-sprite 's_bolt  ss_mine 1 12 #f 170 )
(kern-mk-sprite 's_hdoor  ss_mine 1 19 #f 0 )
(kern-mk-sprite 's_hdoor_locked  ss_mine 1 20 #f 0 )
(kern-mk-sprite 's_portcullis_down  ss_mine 1 21 #f 0 )
(kern-mk-sprite 's_portcullis_up  ss_mine 1 22 #f 0 )
(kern-mk-sprite 's_forest_yellow  ss_mine 1 23 #f 0 )
(kern-mk-sprite 's_L_lever_up  ss_mine 1 24 #f 0 )
(kern-mk-sprite 's_L_lever_down  ss_mine 1 25 #f 0 )
(kern-mk-sprite 's_R_lever_up  ss_mine 1 26 #f 0 )
(kern-mk-sprite 's_R_lever_down  ss_mine 1 27 #f 0 )
(kern-mk-sprite 's_floor_plate  ss_mine 1 28 #f 0 )
(kern-mk-sprite 's_vert_bridge  ss_mine 1 29 #f 0 )
(kern-mk-sprite 's_forest_purple  ss_mine 1 30 #f 0 )
(kern-mk-sprite 's_forest_red  ss_mine 1 31 #f 0 )
(kern-mk-sprite 's_trees_orange  ss_mine 1 32 #f 0 )
(kern-mk-sprite 's_trees_yellow  ss_mine 1 33 #f 0 )
(kern-mk-sprite 's_trees_purple  ss_mine 1 34 #f 0 )
(kern-mk-sprite 's_trees_red  ss_mine 1 35 #f 0 )
(kern-mk-sprite 's_bed  ss_mine 1 36 #f 0 )
(kern-mk-sprite 's_fireplace  ss_mine 2 37 #f 0 )
(kern-mk-sprite 's_green_townsman  ss_mine 2 40 #f 0 )
(kern-mk-sprite 's_yellow_slime  ss_mine 4 42 #f 0 )
(kern-mk-sprite 's_yellow_slime_asleep  ss_mine 1 42 #f 0 )
(kern-mk-sprite 's_wall_torch  ss_mine 2 46 #f 0 )
(kern-mk-sprite 's_water_elemental  ss_mine 1 48 #t 0 )
(kern-mk-sprite 's_closed_solid_wood_door_in_stone  ss_mine 1 49 #f 0 )
(kern-mk-sprite 's_open_solid_wood_door_in_stone  ss_mine 1 50 #f 0 )
(kern-mk-sprite 's_locked_solid_wood_door_in_stone  ss_mine 1 51 #f 0 )
(kern-mk-sprite 's_magically_locked_solid_wood_door_in_stone  ss_mine 3 52 #f 
                0)
(kern-mk-sprite 's_closed_solid_wood_door_in_rock  ss_mine 1 56 #f 0 )
(kern-mk-sprite 's_open_solid_wood_door_in_rock  ss_mine 1 57 #f 0 )
(kern-mk-sprite 's_locked_solid_wood_door_in_rock  ss_mine 1 58 #f 0 )
(kern-mk-sprite 's_magically_locked_solid_wood_door_in_rock  ss_mine 3 59 #f 0)
(kern-mk-sprite 's_arrow_slit  ss_mine 1 62 #f 0 )
(kern-mk-sprite 's_window_in_stone  ss_mine 1 63 #f 0 )
(kern-mk-sprite 's_trail_0  ss_mine 1 64 #f 0 )
(kern-mk-sprite 's_trail_1  ss_mine 1 65 #f 0 )
(kern-mk-sprite 's_trail_2  ss_mine 1 66 #f 0 )
(kern-mk-sprite 's_trail_3  ss_mine 1 67 #f 0 )
(kern-mk-sprite 's_trail_4  ss_mine 1 72 #f 0 )
(kern-mk-sprite 's_trail_5  ss_mine 1 73 #f 0 )
(kern-mk-sprite 's_trail_6  ss_mine 1 74 #f 0 )
(kern-mk-sprite 's_trail_7  ss_mine 1 75 #f 0 )
(kern-mk-sprite 's_trail_8  ss_mine 1 80 #f 0 )
(kern-mk-sprite 's_trail_9  ss_mine 1 81 #f 0 )
(kern-mk-sprite 's_trail_a  ss_mine 1 82 #f 0 )
(kern-mk-sprite 's_trail_b  ss_mine 1 83 #f 0 )
(kern-mk-sprite 's_trail_c  ss_mine 1 88 #f 0 )
(kern-mk-sprite 's_trail_d  ss_mine 1 89 #f 0 )
(kern-mk-sprite 's_trail_e  ss_mine 1 90 #f 0 )
(kern-mk-sprite 's_trail_f  ss_mine 1 91 #f 0 )

;; SAM: Same frame sprites, organized geometraically (plus vbars)
; (kern-mk-sprite 's_frame_ulc   ss_frame 1  0 #f 0 )
; (kern-mk-sprite 's_frame_td    ss_frame 1  1 #f 0 )
; (kern-mk-sprite 's_frame_urc   ss_frame 1  2 #f 0 )
; (kern-mk-sprite 's_frame_endu  ss_frame 1  3 #f 0 )  ; top of vertical bar, currently unused
; (kern-mk-sprite 's_frame_tr    ss_frame 1  4 #f 0 )
; (kern-mk-sprite 's_frame_plus  ss_frame 1  5 #f 0 )  ; center crosspiece, currently unused
; (kern-mk-sprite 's_frame_tl    ss_frame 1  6 #f 0 )
; (kern-mk-sprite 's_frame_vert  ss_frame 1  7 #f 0 )
; (kern-mk-sprite 's_frame_llc   ss_frame 1  8 #f 0 )
; (kern-mk-sprite 's_frame_tu    ss_frame 1  9 #f 0 )
; (kern-mk-sprite 's_frame_lrc   ss_frame 1 10 #f 0 )
; (kern-mk-sprite 's_frame_endb  ss_frame 1 11 #f 0 )  ; bottom of vertical bar, currently unused
; (kern-mk-sprite 's_frame_endl  ss_frame 1 12 #f 0 )
; (kern-mk-sprite 's_frame_horz  ss_frame 1 13 #f 0 )
; (kern-mk-sprite 's_frame_endr  ss_frame 1 14 #f 0 )
; (kern-mk-sprite 's_frame_dot   ss_frame 1 15 #f 0 )  ; disconnected disk, currently unused

(kern-mk-sprite 's_frame_ulc   ss_frame_orig 1 0 #f 0)
(kern-mk-sprite 's_frame_llc   ss_frame_orig 1 1 #f 0 )
(kern-mk-sprite 's_frame_urc   ss_frame_orig 1 2 #f 0 )
(kern-mk-sprite 's_frame_lrc   ss_frame_orig 1 3 #f 0 )
(kern-mk-sprite 's_frame_horz  ss_frame_orig 1 4 #f 0 )
(kern-mk-sprite 's_frame_vert  ss_frame_orig 1 5 #f 0 )
(kern-mk-sprite 's_frame_td    ss_frame_orig 1 6 #f 0 )
(kern-mk-sprite 's_frame_tr    ss_frame_orig 1 7 #f 0 )
(kern-mk-sprite 's_frame_tu    ss_frame_orig 1 8 #f 0 )
(kern-mk-sprite 's_frame_tl    ss_frame_orig 1 9 #f 0 )
(kern-mk-sprite 's_frame_endl  ss_frame_orig 1 10 #f 0 )
(kern-mk-sprite 's_frame_endr  ss_frame_orig 1 11 #f 0 )

(kern-mk-sprite 's_full_moon  ss_moons 1 0 #f 0 )
(kern-mk-sprite 's_wane_three_quarter_moon  ss_moons 1 1 #f 0 )
(kern-mk-sprite 's_wane_half_moon  ss_moons 1 2 #f 0 )
(kern-mk-sprite 's_wane_quarter_moon  ss_moons 1 3 #f 0 )
(kern-mk-sprite 's_new_moon  ss_moons 1 4 #f 0 )
(kern-mk-sprite 's_wax_quarter_moon  ss_moons 1 5 #f 0 )
(kern-mk-sprite 's_wax_half_moon  ss_moons 1 6 #f 0 )
(kern-mk-sprite 's_wax_three_quarter_moon  ss_moons 1 7 #f 0 )
(kern-mk-sprite 's_sun  ss_moons 1 8 #f 0 )

(kern-mk-sprite 's_left_lever_up  ss_mechanisms 1 0 #f 0 )
(kern-mk-sprite 's_left_lever_down  ss_mechanisms 1 1 #f 0 )
(kern-mk-sprite 's_top_lever_left  ss_mechanisms 1 2 #f 0 )
(kern-mk-sprite 's_top_lever_right  ss_mechanisms 1 3 #f 0 )
(kern-mk-sprite 's_right_lever_up  ss_mechanisms 1 4 #f 0 )
(kern-mk-sprite 's_right_lever_down  ss_mechanisms 1 5 #f 0 )
(kern-mk-sprite 's_bottom_lever_left  ss_mechanisms 1 6 #f 0 )
(kern-mk-sprite 's_bottom_lever_right  ss_mechanisms 1 7 #f 0 )
(kern-mk-sprite 's_floor_plate  ss_mechanisms 1 8 #f 0 )
(kern-mk-sprite 's_floor_lever_left  ss_mechanisms 1 10 #f 0 )
(kern-mk-sprite 's_floor_lever_right  ss_mechanisms 1 11 #f 0 )

(kern-mk-sprite 'ls_ankh  ss_little_sprites 1 0 #f 0 )
(kern-mk-sprite 'ls_shield  ss_little_sprites 1 1 #f 0 )
(kern-mk-sprite 'ls_holey_wall  ss_little_sprites 1 2 #f 0 )
(kern-mk-sprite 'ls_wall  ss_little_sprites 1 3 #f 0 )
(kern-mk-sprite 'ls_updown_arrow  ss_little_sprites 1 4 #f 0 )
(kern-mk-sprite 'ls_down_arrow  ss_little_sprites 1 5 #f 0 )
(kern-mk-sprite 'ls_up_arrow  ss_little_sprites 1 6 #f 0 )
(kern-mk-sprite 'ls_holey_ankh  ss_little_sprites 1 7 #f 0 )
(kern-mk-sprite 'ls_white_ball  ss_little_sprites 1 8 #f 0 )
(kern-mk-sprite 'ls_copyright  ss_little_sprites 1 9 #f 0 )
(kern-mk-sprite 'ls_trademark  ss_little_sprites 1 10 #f 0 )
(kern-mk-sprite 'ls_male  ss_little_sprites 1 11 #f 0 )
(kern-mk-sprite 'ls_female  ss_little_sprites 1 12 #f 0 )
(kern-mk-sprite 'ls_hbar  ss_little_sprites 1 13 #f 0 )
(kern-mk-sprite 'ls_vbar  ss_little_sprites 1 13 #f 0 )
(kern-mk-sprite 'ls_square  ss_little_sprites 1 14 #f 0 )
(kern-mk-sprite 'ls_blue_ball  ss_little_sprites 1 15 #f 0 )
(kern-mk-sprite 'ls_hbar_right  ss_little_sprites 1 16 #f 0 )
(kern-mk-sprite 'ls_hbar_left  ss_little_sprites 1 17 #f 0 )
(kern-mk-sprite 'ls_vbar_top  ss_little_sprites 1 16 #f 0 )
(kern-mk-sprite 'ls_vbar_bottom  ss_little_sprites 1 17 #f 0 )
(kern-mk-sprite 'ls_blank_one  ss_little_sprites 1 18 #f 0 )
(kern-mk-sprite 'ls_dot_dot_dot  ss_little_sprites 1 19 #f 0 )
(kern-mk-sprite 'ls_whirlpool  ss_little_sprites 4 28 #f 0 )
(kern-mk-sprite 'ls_blank_three  ss_little_sprites 1 32 #f 0 )

(kern-mk-sprite 's_rune_A  ss_rune_font_32x32 1 0 #f 0 )
(kern-mk-sprite 's_rune_B  ss_rune_font_32x32 1 1 #f 0 )
(kern-mk-sprite 's_rune_C  ss_rune_font_32x32 1 2 #f 0 )
(kern-mk-sprite 's_rune_D  ss_rune_font_32x32 1 3 #f 0 )
(kern-mk-sprite 's_rune_E  ss_rune_font_32x32 1 4 #f 0 )
(kern-mk-sprite 's_rune_F  ss_rune_font_32x32 1 5 #f 0 )
(kern-mk-sprite 's_rune_G  ss_rune_font_32x32 1 6 #f 0 )
(kern-mk-sprite 's_rune_H  ss_rune_font_32x32 1 7 #f 0 )
(kern-mk-sprite 's_rune_I  ss_rune_font_32x32 1 8 #f 0 )
(kern-mk-sprite 's_rune_J  ss_rune_font_32x32 1 9 #f 0 )
(kern-mk-sprite 's_rune_K  ss_rune_font_32x32 1 10 #f 0 )
(kern-mk-sprite 's_rune_L  ss_rune_font_32x32 1 11 #f 0 )
(kern-mk-sprite 's_rune_M  ss_rune_font_32x32 1 12 #f 0 )
(kern-mk-sprite 's_rune_N  ss_rune_font_32x32 1 13 #f 0 )
(kern-mk-sprite 's_rune_O  ss_rune_font_32x32 1 14 #f 0 )
(kern-mk-sprite 's_rune_P  ss_rune_font_32x32 1 15 #f 0 )
(kern-mk-sprite 's_rune_Q  ss_rune_font_32x32 1 16 #f 0 )
(kern-mk-sprite 's_rune_R  ss_rune_font_32x32 1 17 #f 0 )
(kern-mk-sprite 's_rune_S  ss_rune_font_32x32 1 18 #f 0 )
(kern-mk-sprite 's_rune_T  ss_rune_font_32x32 1 19 #f 0 )
(kern-mk-sprite 's_rune_U  ss_rune_font_32x32 1 20 #f 0 )
(kern-mk-sprite 's_rune_V  ss_rune_font_32x32 1 21 #f 0 )
(kern-mk-sprite 's_rune_W  ss_rune_font_32x32 1 22 #f 0 )
(kern-mk-sprite 's_rune_X  ss_rune_font_32x32 1 23 #f 0 )
(kern-mk-sprite 's_rune_Y  ss_rune_font_32x32 1 24 #f 0 )
(kern-mk-sprite 's_rune_Z  ss_rune_font_32x32 1 25 #f 0 )
(kern-mk-sprite 's_rune_TH  ss_rune_font_32x32 1 26 #f 0 )
(kern-mk-sprite 's_rune_EE  ss_rune_font_32x32 1 27 #f 0 )
(kern-mk-sprite 's_rune_NG  ss_rune_font_32x32 1 28 #f 0 )
(kern-mk-sprite 's_rune_EA  ss_rune_font_32x32 1 29 #f 0 )
(kern-mk-sprite 's_rune_ST  ss_rune_font_32x32 1 30 #f 0 )
(kern-mk-sprite 's_rune_DOTSEP  ss_rune_font_32x32 1 31 #f 0 )

(kern-mk-sprite 'ls_rune_A  ss_rune_font_8x16 1 0 #f 0 )
(kern-mk-sprite 'ls_rune_B  ss_rune_font_8x16 1 1 #f 0 )
(kern-mk-sprite 'ls_rune_C  ss_rune_font_8x16 1 2 #f 0 )
(kern-mk-sprite 'ls_rune_D  ss_rune_font_8x16 1 3 #f 0 )
(kern-mk-sprite 'ls_rune_E  ss_rune_font_8x16 1 4 #f 0 )
(kern-mk-sprite 'ls_rune_F  ss_rune_font_8x16 1 5 #f 0 )
(kern-mk-sprite 'ls_rune_G  ss_rune_font_8x16 1 6 #f 0 )
(kern-mk-sprite 'ls_rune_H  ss_rune_font_8x16 1 7 #f 0 )
(kern-mk-sprite 'ls_rune_I  ss_rune_font_8x16 1 8 #f 0 )
(kern-mk-sprite 'ls_rune_J  ss_rune_font_8x16 1 9 #f 0 )
(kern-mk-sprite 'ls_rune_K  ss_rune_font_8x16 1 10 #f 0 )
(kern-mk-sprite 'ls_rune_L  ss_rune_font_8x16 1 11 #f 0 )
(kern-mk-sprite 'ls_rune_M  ss_rune_font_8x16 1 12 #f 0 )
(kern-mk-sprite 'ls_rune_N  ss_rune_font_8x16 1 13 #f 0 )
(kern-mk-sprite 'ls_rune_O  ss_rune_font_8x16 1 14 #f 0 )
(kern-mk-sprite 'ls_rune_P  ss_rune_font_8x16 1 15 #f 0 )
(kern-mk-sprite 'ls_rune_Q  ss_rune_font_8x16 1 16 #f 0 )
(kern-mk-sprite 'ls_rune_R  ss_rune_font_8x16 1 17 #f 0 )
(kern-mk-sprite 'ls_rune_S  ss_rune_font_8x16 1 18 #f 0 )
(kern-mk-sprite 'ls_rune_T  ss_rune_font_8x16 1 19 #f 0 )
(kern-mk-sprite 'ls_rune_U  ss_rune_font_8x16 1 20 #f 0 )
(kern-mk-sprite 'ls_rune_V  ss_rune_font_8x16 1 21 #f 0 )
(kern-mk-sprite 'ls_rune_W  ss_rune_font_8x16 1 22 #f 0 )
(kern-mk-sprite 'ls_rune_X  ss_rune_font_8x16 1 23 #f 0 )
(kern-mk-sprite 'ls_rune_Y  ss_rune_font_8x16 1 24 #f 0 )
(kern-mk-sprite 'ls_rune_Z  ss_rune_font_8x16 1 25 #f 0 )
(kern-mk-sprite 'ls_rune_TH  ss_rune_font_8x16 1 26 #f 0 )
(kern-mk-sprite 'ls_rune_EE  ss_rune_font_8x16 1 27 #f 0 )
(kern-mk-sprite 'ls_rune_NG  ss_rune_font_8x16 1 28 #f 0 )
(kern-mk-sprite 'ls_rune_EA  ss_rune_font_8x16 1 29 #f 0 )
(kern-mk-sprite 'ls_rune_ST  ss_rune_font_8x16 1 30 #f 0 )
(kern-mk-sprite 'ls_rune_DOTSEP  ss_rune_font_8x16 1 31 #f 0 )

(kern-mk-sprite 's_dresser  ss_lost_dragon 1 0 #f 0 )
(kern-mk-sprite 's_chair  ss_lost_dragon 1 1 #f 0 )

(kern-mk-sprite 's_gold_explosion ss_angband 1 61 #f 0 )
(kern-mk-sprite 's_brown_powder ss_angband 1 113 #f 0 )
(kern-mk-sprite 's_silver_powder ss_angband 1 114 #f 0 )
(kern-mk-sprite 's_gold_powder ss_angband 1 115 #f 0 )
(kern-mk-sprite 's_bluish_white_powder ss_angband 1 116 #f 0 )
(kern-mk-sprite 's_greenish_white_powder ss_angband 1 117 #f 0 )
(kern-mk-sprite 's_grayish_red_hunks ss_angband 1 118 #f 0 )
(kern-mk-sprite 's_white_hunks ss_angband 1 119 #f 0 )
(kern-mk-sprite 's_aquamarine_hunks ss_angband 1 120 #f 0 )
(kern-mk-sprite 's_red_hunks ss_angband 1 121 #f 0 )
(kern-mk-sprite 's_lightblue_hunks ss_angband 1 122 #f 0 )
(kern-mk-sprite 's_green_hunks ss_angband 1 123 #f 0 )
(kern-mk-sprite 's_scroll1 ss_angband 1 124 #f 0 )
(kern-mk-sprite 's_scroll2 ss_angband 1 125 #f 0 )
(kern-mk-sprite 's_scroll3 ss_angband 1 126 #f 0 )
(kern-mk-sprite 's_scroll4 ss_angband 1 127 #f 0 )
(kern-mk-sprite 's_ring1 ss_angband 1 128 #f 0 )
(kern-mk-sprite 's_ring2 ss_angband 1 129 #f 0 )
(kern-mk-sprite 's_ring3 ss_angband 1 130 #f 0 )
(kern-mk-sprite 's_ring4 ss_angband 1 131 #f 0 )
(kern-mk-sprite 's_ring5 ss_angband 1 132 #f 0 )
(kern-mk-sprite 's_ring6 ss_angband 1 133 #f 0 )
(kern-mk-sprite 's_ring7 ss_angband 1 134 #f 0 )
(kern-mk-sprite 's_ring8 ss_angband 1 135 #f 0 )
(kern-mk-sprite 's_ring9 ss_angband 1 136 #f 0 )
(kern-mk-sprite 's_ring10 ss_angband 1 137 #f 0 )
(kern-mk-sprite 's_ring11 ss_angband 1 138 #f 0 )
(kern-mk-sprite 's_ring12 ss_angband 1 139 #f 0 )
(kern-mk-sprite 's_ring13 ss_angband 1 140 #f 0 )
(kern-mk-sprite 's_ring14 ss_angband 1 141 #f 0 )
(kern-mk-sprite 's_ring15 ss_angband 1 142 #f 0 )
(kern-mk-sprite 's_ring16 ss_angband 1 143 #f 0 )
(kern-mk-sprite 's_ring17 ss_angband 1 145 #f 0 )
(kern-mk-sprite 's_ring18 ss_angband 1 146 #f 0 )
(kern-mk-sprite 's_ring19 ss_angband 1 147 #f 0 )
(kern-mk-sprite 's_ring20 ss_angband 1 148 #f 0 )
(kern-mk-sprite 's_ring21 ss_angband 1 149 #f 0 )
(kern-mk-sprite 's_necklace1 ss_angband 1 150 #f 0 )
(kern-mk-sprite 's_necklace2 ss_angband 1 151 #f 0 )
(kern-mk-sprite 's_necklace3 ss_angband 1 152 #f 0 )
(kern-mk-sprite 's_small_wooden_chest ss_angband 1 153 #f 0 )
(kern-mk-sprite 's_large_wooden_chest ss_angband 1 154 #f 0 )
(kern-mk-sprite 's_small_gray_chest ss_angband 1 155 #f 0 )
(kern-mk-sprite 's_large_gray_chest ss_angband 1 156 #f 0 )
(kern-mk-sprite 's_small_silver_chest ss_angband 1 157 #f 0 )
(kern-mk-sprite 's_large_silver_chest ss_angband 1 158 #f 0 )
(kern-mk-sprite 's_junk_pile ss_angband 1 159 #f 0 )
(kern-mk-sprite 's_white_potion ss_angband 1 160 #f 0 )
(kern-mk-sprite 's_black_potion ss_angband 1 161 #f 0 )
(kern-mk-sprite 's_orange_potion ss_angband 1 162 #f 0 )
(kern-mk-sprite 's_red_potion ss_angband 1 163 #f 0 )
(kern-mk-sprite 's_green_potion ss_angband 1 164 #f 0 )
(kern-mk-sprite 's_blue_potion ss_angband 1 165 #f 0 )
(kern-mk-sprite 's_brown_potion ss_angband 1 166 #f 0 )
(kern-mk-sprite 's_gray_potion ss_angband 1 167 #f 0 )
(kern-mk-sprite 's_silver_potion ss_angband 1 168 #f 0 )
(kern-mk-sprite 's_purple_potion ss_angband 1 169 #f 0 )
(kern-mk-sprite 's_yellow_potion ss_angband 1 170 #f 0 )
(kern-mk-sprite 's_ruby_potion ss_angband 1 171 #f 0 )
(kern-mk-sprite 's_emarald_potion ss_angband 1 172 #f 0 )
(kern-mk-sprite 's_skyblue_potion ss_angband 1 173 #f 0 )
(kern-mk-sprite 's_golden_potion ss_angband 1 174 #f 0 )
(kern-mk-sprite 's_silver_mushroom ss_angband 1 176 #f 0 )
(kern-mk-sprite 's_charcoal_mushroom ss_angband 1 177 #f 0 )
(kern-mk-sprite 's_orange_mushroom ss_angband 1 178 #f 0 )
(kern-mk-sprite 's_blood_mushroom ss_angband 1 179 #f 0 )
(kern-mk-sprite 's_olive_mushroom ss_angband 1 180 #f 0 )
(kern-mk-sprite 's_turqoise_mushroom ss_angband 1 181 #f 0 )
(kern-mk-sprite 's_brown_mushroom ss_angband 1 182 #f 0 )
(kern-mk-sprite 's_black_mushroom ss_angband 1 183 #f 0 )
(kern-mk-sprite 's_gray_mushroom ss_angband 1 184 #f 0 )
(kern-mk-sprite 's_purple_mushroom ss_angband 1 185 #f 0 )
(kern-mk-sprite 's_golden_mushroom ss_angband 1 186 #f 0 )
(kern-mk-sprite 's_ruby_mushroom ss_angband 1 187 #f 0 )
(kern-mk-sprite 's_verdant_mushroom ss_angband 1 188 #f 0 )
(kern-mk-sprite 's_blue_mushroom ss_angband 1 189 #f 0 )
(kern-mk-sprite 's_sandy_mushroom ss_angband 1 190 #f 0 )
(kern-mk-sprite 's_leather_hood ss_angband 1 248 #f 0 )
(kern-mk-sprite 's_chain_coif ss_angband 1 249 #f 0 )
(kern-mk-sprite 's_helm3 ss_angband 1 250 #f 0 )
(kern-mk-sprite 's_helm4 ss_angband 1 251 #f 0 )
(kern-mk-sprite 's_helm5 ss_angband 1 252 #f 0 )
(kern-mk-sprite 's_helm6 ss_angband 1 253 #f 0 )
(kern-mk-sprite 's_helm7 ss_angband 1 254 #f 0 )
(kern-mk-sprite 's_spiked_helm ss_angband 1 255 #f 0 )
(kern-mk-sprite 's_plate_helm ss_angband 1 256 #f 0 )
(kern-mk-sprite 's_helm10 ss_angband 1 257 #f 0 )
(kern-mk-sprite 's_helm11 ss_angband 1 258 #f 0 )
(kern-mk-sprite 's_helm12 ss_angband 1 259 #f 0 )
(kern-mk-sprite 's_helm13 ss_angband 1 260 #f 0 )
(kern-mk-sprite 's_helm14 ss_angband 1 261 #f 0 )
(kern-mk-sprite 's_helm15 ss_angband 1 262 #f 0 )
(kern-mk-sprite 's_helm16 ss_angband 1 263 #f 0 )
(kern-mk-sprite 's_helm17 ss_angband 1 264 #f 0 )
(kern-mk-sprite 's_helm18 ss_angband 1 265 #f 0 )
(kern-mk-sprite 's_helm19 ss_angband 1 266 #f 0 )
(kern-mk-sprite 's_helm20 ss_angband 1 267 #f 0 )
(kern-mk-sprite 's_helm21 ss_angband 1 268 #f 0 )
(kern-mk-sprite 's_helm22 ss_angband 1 269 #f 0 )
(kern-mk-sprite 's_shoes ss_angband 1 270 #f 0 )
(kern-mk-sprite 's_leather_boots ss_angband 1 271 #f 0 )
(kern-mk-sprite 's_plate_boots ss_angband 1 272 #f 0 )
(kern-mk-sprite 's_leather_gauntlets ss_angband 1 273 #f 0 )
(kern-mk-sprite 's_plate_gauntlets ss_angband 1 274 #f 0 )
(kern-mk-sprite 's_black_gauntlets ss_angband 1 275 #f 0 )
(kern-mk-sprite 's_small_shield ss_angband 1 276 #f 0 )
(kern-mk-sprite 's_large_shield ss_angband 1 277 #f 0 )
(kern-mk-sprite 's_shield3 ss_angband 1 278 #f 0 )
(kern-mk-sprite 's_shield4 ss_angband 1 279 #f 0 )
(kern-mk-sprite 's_shield5 ss_angband 1 280 #f 0 )
(kern-mk-sprite 's_spiked_shield ss_angband 1 281 #f 0 )
(kern-mk-sprite 's_shield7 ss_angband 1 282 #f 0 )
(kern-mk-sprite 's_shield8 ss_angband 1 283 #f 0 )
(kern-mk-sprite 's_shield9 ss_angband 1 284 #f 0 )
(kern-mk-sprite 's_shield10 ss_angband 1 285 #f 0 )
(kern-mk-sprite 's_shield11 ss_angband 1 286 #f 0 )
(kern-mk-sprite 's_shield12 ss_angband 1 287 #f 0 )
(kern-mk-sprite 's_shield13 ss_angband 1 288 #f 0 )
(kern-mk-sprite 's_shield14 ss_angband 1 289 #f 0 )
(kern-mk-sprite 's_shield15 ss_angband 1 290 #f 0 )
(kern-mk-sprite 's_shield16 ss_angband 1 291 #f 0 )
(kern-mk-sprite 's_shield17 ss_angband 1 292 #f 0 )
(kern-mk-sprite 's_shield18 ss_angband 1 293 #f 0 )
(kern-mk-sprite 's_shield19 ss_angband 1 294 #f 0 )
(kern-mk-sprite 's_shield20 ss_angband 1 295 #f 0 )
(kern-mk-sprite 's_dagger ss_angband 1 334 #f 0 )
(kern-mk-sprite 's_sword ss_angband 1 345 #f 0 )
(kern-mk-sprite 's_hand_axe ss_angband 1 368 #f 0 )
(kern-mk-sprite 's_long_sword ss_angband 1 1708 #f 0 )
(kern-mk-sprite 's_2h_sword ss_angband 1 1709 #f 0 )
(kern-mk-sprite 's_2h_hammer ss_angband 1 352 #f 0 )
(kern-mk-sprite 's_mace ss_angband 1 353 #f 0 )
(kern-mk-sprite 's_staff ss_angband 1 354 #f 0 )
(kern-mk-sprite 's_iron_handled_morning_star ss_angband 1 355 #f 0 )
(kern-mk-sprite 's_wood_handled_morning_star ss_angband 1 356 #f 0 )
(kern-mk-sprite 's_fat_knife ss_angband 1 357 #f 0 )
(kern-mk-sprite 's_ball_and_chain ss_angband 1 358 #f 0 )
(kern-mk-sprite 's_red_handled_morning_star ss_angband 1 359 #f 0 )
(kern-mk-sprite 's_ruby_mace ss_angband 1 360 #f 0 )
(kern-mk-sprite 's_spear ss_angband 1 361 #f 0 )
(kern-mk-sprite 's_lght_bow ss_angband 1 376 #f 0 )
(kern-mk-sprite 's_hvy_bow ss_angband 1 377 #f 0 )
(kern-mk-sprite 's_lght_xbow ss_angband 1 378 #f 0 )
(kern-mk-sprite 's_hvy_xbow ss_angband 1 379 #f 0 )
(kern-mk-sprite 's_sling ss_angband 1 380 #f 0 )
(kern-mk-sprite 's_hard_leather ss_angband 1 305 #f 0 )
(kern-mk-sprite 's_ring_mail ss_angband 1 309 #f 0 )
(kern-mk-sprite 's_plate_armor ss_angband 1 316 #f 0 )
(kern-mk-sprite 's_torch ss_angband 1 459 #f 0 )
(kern-mk-sprite 's_explosion ss_angband 1 570 #f 0 )
(kern-mk-sprite 's_giant ss_angband 2 652 #f 0 )
(kern-mk-sprite 's_red_magbolt    ss_angband 1 480 #f 170)
(kern-mk-sprite 's_blue_magbolt   ss_angband 1 484 #f 170)
(kern-mk-sprite 's_cyan_magbolt   ss_angband 1 488 #f 170)
(kern-mk-sprite 's_green_magbolt  ss_angband 1 492 #f 170)
(kern-mk-sprite 's_gray_magbolt   ss_angband 1 496 #f 170)
(kern-mk-sprite 's_purple_magbolt ss_angband 1 500 #f 170)
(kern-mk-sprite 's_gold_magbolt   ss_angband 1 504 #f 170)
(kern-mk-sprite 's_black_magbolt  ss_angband 1 508 #f 170)
(kern-mk-sprite 's_gold_explosion ss_angband 1 558 #f 0)
