;;----------------------------------------------------------------------------
;; Terrains
;;----------------------------------------------------------------------------

;; Terrain effect procedures. These are assigned to terrains so that whenever
;; an object "steps" (or is dropped or placed) on that terrain the procedure
;; runs with the object as a parameter.

(define (terrain-effect-burn obj)
  (kern-obj-apply-damage obj "burning" 10))

;; kern-mk-terrain
;;      tag: variable name to reference terrain elsewhere in the script
;;     name: name presented to UI
;;    pmask: objective passablity mask (permitted bits set)
;;   sprite: animated image
;;    alpha: true if terrain blocks los
;;     cost: base movement cost (in action points)
;;    light: radiated light strength
;;   effect: optional procedure to run when an object is placed on the terrain,
;;           takes the object as it's sole argument

(kern-mk-terrain 't_lava            "lava"          pmask-land   s_lava            1 3  128 'burn)
(kern-mk-terrain 't_deep            "deep water"    pmask-water  s_deep            1 2  0 nil)
(kern-mk-terrain 't_shallow         "shallow water" pmask-water  s_shallow         1 2  0 nil)
(kern-mk-terrain 't_shoals          "shoals"        pmask-shoals s_shoals          1 2  0 nil)
(kern-mk-terrain 't_grass           "grass"         pmask-land   s_grass           1 2  0 nil)
(kern-mk-terrain 't_trees           "trees"         pmask-land   s_trees           1 2  0 nil)
(kern-mk-terrain 't_forest          "forest"        pmask-land   s_forest          0 4  0 nil)
(kern-mk-terrain 't_hills           "hills"         pmask-land   s_hills           1 3  0 nil)
(kern-mk-terrain 't_mountains       "mountains"     pmask-solid  s_mountains       0 4  0 nil)
(kern-mk-terrain 't_leftwing        "castle wall"   pmask-solid  s_leftwing        1 2  0 nil)
(kern-mk-terrain 't_rightwing       "castle wall"   pmask-solid  s_rightwing       1 2  0 nil)
(kern-mk-terrain 't_cobblestone     "cobblestone"   pmask-land   s_cobblestone     1 2  0 nil)
(kern-mk-terrain 't_flagstones      "flagstones"    pmask-land   s_flagstone       1 2  0 nil)
(kern-mk-terrain 't_bog             "bog"           pmask-land   s_bog             1 3  0 nil)
(kern-mk-terrain 't_fire_terrain    "fire"          pmask-land   s_field_fire      1 2  512  'burn)
(kern-mk-terrain 't_fireplace       "fireplace"     pmask-land   s_fireplace       1 2  2048 'burn)
(kern-mk-terrain 't_bridge          "bridge"        pmask-bridge s_bridge          1 2  0 nil)
(kern-mk-terrain 't_bridge_top      "bridge"        pmask-bridge s_bridge_top      1 2  0 nil)
(kern-mk-terrain 't_bridge_bottom   "bridge"        pmask-bridge s_bridge_bottom   1 2  0 nil)
(kern-mk-terrain 't_ship_hull       "ship's hull"   pmask-solid  s_wall            1 0  0 nil)
(kern-mk-terrain 't_sh_hull_NE      "ship's hull"   pmask-solid  s_wall_b          1 2  0 nil)
(kern-mk-terrain 't_sh_hull_NW      "ship's hull"   pmask-solid  s_wall_a          1 2  0 nil)
(kern-mk-terrain 't_sh_hull_SE      "ship's hull"   pmask-solid  s_wall_c          1 2  0 nil)
(kern-mk-terrain 't_sh_hull_SW      "ship's hull"   pmask-solid  s_wall_d          1 2  0 nil)
(kern-mk-terrain 't_mast            "mast"          pmask-solid  s_mast            1 2  0 nil)
(kern-mk-terrain 't_ships_wheel     "ship's wheel"  pmask-solid  s_ships_wheel     1 2  0 nil)
(kern-mk-terrain 't_deck            "deck"          pmask-land   s_deck            1 2  0 nil)
(kern-mk-terrain 't_wall_rock       "rock wall"     pmask-solid  s_wall_rock       0 2  0 nil)
(kern-mk-terrain 't_wall            "wall"          pmask-solid  s_wall_stone      0 2  0 nil)
(kern-mk-terrain 't_wall_torch      "wall torch"    pmask-solid  s_wall_torch      0 2  512 'burn)
(kern-mk-terrain 't_secret_door     "secret door"   pmask-land   s_secret_door     0 2  0 nil)
(kern-mk-terrain 't_sea_wall        "sea wall"      pmask-solid  s_wall            0 2  0 nil)
(kern-mk-terrain 't_sea_wall_NE     "sea wall"      pmask-solid  s_wall_b          0 2  0 nil)
(kern-mk-terrain 't_sea_wall_NW     "sea wall"      pmask-solid  s_wall_a          0 2  0 nil)
(kern-mk-terrain 't_sea_wall_SE     "sea wall"      pmask-solid  s_wall_c          0 2  0 nil)
(kern-mk-terrain 't_sea_wall_SW     "sea wall"      pmask-solid  s_wall_d          0 2  0 nil)
(kern-mk-terrain 't_boulder         "boulder"       pmask-solid  s_boulder         1 2  0 nil)
(kern-mk-terrain 't_ankh            "ankh"          pmask-solid  s_ankh            1 2  0 nil)
(kern-mk-terrain 't_altar           "altar"         pmask-solid  s_altar           1 2  0 nil)
(kern-mk-terrain 't_pillar          "pillar"        pmask-solid  s_pillar          1 2  0 nil)
(kern-mk-terrain 't_counter_middle  "counter"       pmask-solid  s_counter_middle  1 2  0 nil)
(kern-mk-terrain 't_counter_right   "counter"       pmask-solid  s_counter_right   1 2  0 nil)
(kern-mk-terrain 't_counter_left    "counter"       pmask-solid  s_counter_left    1 2  0 nil)
(kern-mk-terrain 't_counter_1x1     "counter"       pmask-solid  s_counter_1x1     1 2  0 nil)
(kern-mk-terrain 't_trail_0         "trail"         pmask-land   s_trail_0         1 2  0 nil)
(kern-mk-terrain 't_trail_1         "trail"         pmask-land   s_trail_1         1 2  0 nil)
(kern-mk-terrain 't_trail_2         "trail"         pmask-land   s_trail_2         1 2  0 nil)
(kern-mk-terrain 't_trail_3         "trail"         pmask-land   s_trail_3         1 2  0 nil)
(kern-mk-terrain 't_trail_4         "trail"         pmask-land   s_trail_4         1 2  0 nil)
(kern-mk-terrain 't_trail_5         "trail"         pmask-land   s_trail_5         1 2  0 nil)
(kern-mk-terrain 't_trail_6         "trail"         pmask-land   s_trail_6         1 2  0 nil)
(kern-mk-terrain 't_trail_7         "trail"         pmask-land   s_trail_7         1 2  0 nil)
(kern-mk-terrain 't_trail_8         "trail"         pmask-land   s_trail_8         1 2  0 nil)
(kern-mk-terrain 't_trail_9         "trail"         pmask-land   s_trail_9         1 2  0 nil)
(kern-mk-terrain 't_trail_a         "trail"         pmask-land   s_trail_a         1 2  0 nil)
(kern-mk-terrain 't_trail_b         "trail"         pmask-land   s_trail_b         1 2  0 nil)
(kern-mk-terrain 't_trail_c         "trail"         pmask-land   s_trail_c         1 2  0 nil)
(kern-mk-terrain 't_trail_d         "trail"         pmask-land   s_trail_d         1 2  0 nil)
(kern-mk-terrain 't_trail_e         "trail"         pmask-land   s_trail_e         1 2  0 nil)
(kern-mk-terrain 't_trail_f         "trail"         pmask-land   s_trail_f         1 2  0 nil)
(kern-mk-terrain 't_A               "an A"          pmask-solid  s_A               1 2  0 nil)
(kern-mk-terrain 't_B               "a B"           pmask-solid  s_B               1 2  0 nil)
(kern-mk-terrain 't_C               "a C"           pmask-solid  s_C               1 2  0 nil)
(kern-mk-terrain 't_D               "a D"           pmask-solid  s_D               1 2  0 nil)
(kern-mk-terrain 't_E               "an E"          pmask-solid  s_E               1 2  0 nil)
(kern-mk-terrain 't_F               "an F"          pmask-solid  s_F               1 2  0 nil)
(kern-mk-terrain 't_G               "a G"           pmask-solid  s_G               1 2  0 nil)
(kern-mk-terrain 't_H               "an H"          pmask-solid  s_H               1 2  0 nil)
(kern-mk-terrain 't_I               "an I"          pmask-solid  s_I               1 2  0 nil)
(kern-mk-terrain 't_J               "a J"           pmask-solid  s_J               1 2  0 nil)
(kern-mk-terrain 't_K               "a K"           pmask-solid  s_K               1 2  0 nil)
(kern-mk-terrain 't_L               "an L"          pmask-solid  s_L               1 2  0 nil)
(kern-mk-terrain 't_M               "an M"          pmask-solid  s_M               1 2  0 nil)
(kern-mk-terrain 't_N               "an N"          pmask-solid  s_N               1 2  0 nil)
(kern-mk-terrain 't_O               "an O"          pmask-solid  s_O               1 2  0 nil)
(kern-mk-terrain 't_P               "a P"           pmask-solid  s_P               1 2  0 nil)
(kern-mk-terrain 't_Q               "a Q"           pmask-solid  s_Q               1 2  0 nil)
(kern-mk-terrain 't_R               "an R"          pmask-solid  s_R               1 2  0 nil)
(kern-mk-terrain 't_S               "an S"          pmask-solid  s_S               1 2  0 nil)
(kern-mk-terrain 't_T               "a T"           pmask-solid  s_T               1 2  0 nil)
(kern-mk-terrain 't_U               "a U"           pmask-solid  s_U               1 2  0 nil)
(kern-mk-terrain 't_V               "a V"           pmask-solid  s_V               1 2  0 nil)
(kern-mk-terrain 't_W               "a W"           pmask-solid  s_W               1 2  0 nil)
(kern-mk-terrain 't_X               "an X"          pmask-solid  s_X               1 2  0 nil)
(kern-mk-terrain 't_Y               "a Y"           pmask-solid  s_Y               1 2  0 nil)
(kern-mk-terrain 't_Z               "a Z"           pmask-solid  s_Z               1 2  0 nil)
(kern-mk-terrain 't_rune_A          "a rune"        pmask-solid  s_rune_A          1 2  0 nil)
(kern-mk-terrain 't_rune_B          "a rune"        pmask-solid  s_rune_B          1 2  0 nil)
(kern-mk-terrain 't_rune_C          "a rune"        pmask-solid  s_rune_C          1 2  0 nil)
(kern-mk-terrain 't_rune_D          "a rune"        pmask-solid  s_rune_D          1 2  0 nil)
(kern-mk-terrain 't_rune_E          "a rune"        pmask-solid  s_rune_E          1 2  0 nil)
(kern-mk-terrain 't_rune_F          "a rune"        pmask-solid  s_rune_F          1 2  0 nil)
(kern-mk-terrain 't_rune_G          "a rune"        pmask-solid  s_rune_G          1 2  0 nil)
(kern-mk-terrain 't_rune_H          "a rune"        pmask-solid  s_rune_H          1 2  0 nil)
(kern-mk-terrain 't_rune_I          "a rune"        pmask-solid  s_rune_I          1 2  0 nil)
(kern-mk-terrain 't_rune_J          "a rune"        pmask-solid  s_rune_J          1 2  0 nil)
(kern-mk-terrain 't_rune_K          "a rune"        pmask-solid  s_rune_K          1 2  0 nil)
(kern-mk-terrain 't_rune_L          "a rune"        pmask-solid  s_rune_L          1 2  0 nil)
(kern-mk-terrain 't_rune_M          "a rune"        pmask-solid  s_rune_M          1 2  0 nil)
(kern-mk-terrain 't_rune_N          "a rune"        pmask-solid  s_rune_N          1 2  0 nil)
(kern-mk-terrain 't_rune_O          "a rune"        pmask-solid  s_rune_O          1 2  0 nil)
(kern-mk-terrain 't_rune_P          "a rune"        pmask-solid  s_rune_P          1 2  0 nil)
(kern-mk-terrain 't_rune_Q          "a rune"        pmask-solid  s_rune_Q          1 2  0 nil)
(kern-mk-terrain 't_rune_R          "a rune"        pmask-solid  s_rune_R          1 2  0 nil)
(kern-mk-terrain 't_rune_S          "a rune"        pmask-solid  s_rune_S          1 2  0 nil)
(kern-mk-terrain 't_rune_T          "a rune"        pmask-solid  s_rune_T          1 2  0 nil)
(kern-mk-terrain 't_rune_U          "a rune"        pmask-solid  s_rune_U          1 2  0 nil)
(kern-mk-terrain 't_rune_V          "a rune"        pmask-solid  s_rune_V          1 2  0 nil)
(kern-mk-terrain 't_rune_W          "a rune"        pmask-solid  s_rune_W          1 2  0 nil)
(kern-mk-terrain 't_rune_X          "a rune"        pmask-solid  s_rune_X          1 2  0 nil)
(kern-mk-terrain 't_rune_Y          "a rune"        pmask-solid  s_rune_Y          1 2  0 nil)
(kern-mk-terrain 't_rune_Z          "a rune"        pmask-solid  s_rune_Z          1 2  0 nil)
(kern-mk-terrain 't_rune_TH         "a rune"        pmask-solid  s_rune_TH         1 2  0 nil)
(kern-mk-terrain 't_rune_EE         "a rune"        pmask-solid  s_rune_EE         1 2  0 nil)
(kern-mk-terrain 't_rune_NG         "a rune"        pmask-solid  s_rune_NG         1 2  0 nil)
(kern-mk-terrain 't_rune_EA         "a rune"        pmask-solid  s_rune_EA         1 2  0 nil)
(kern-mk-terrain 't_rune_ST         "a rune"        pmask-solid  s_rune_ST         1 2  0 nil)
(kern-mk-terrain 't_rune_DOT        "a rune"        pmask-solid  s_rune_DOTSEP     1 2  0 nil)
(kern-mk-terrain 't_red_roses       "roses"         pmask-land   s_trees_red       1 2  0 nil)
(kern-mk-terrain 't_arrow_slit      "arrow slit"    pmask-solid  s_arrow_slit      1 2  0 nil)
(kern-mk-terrain 't_window_in_stone "window"        pmask-solid  s_window_in_stone 1 2  0 nil)
