;;----------------------------------------------------------------------------
;; Terrains
;;----------------------------------------------------------------------------

;; Terrain effect procedures. These are assigned to terrains so that whenever
;; an object "steps" (or is dropped or placed) on that terrain the procedure
;; runs with the object as a parameter.

(define (terrain-effect-burn obj)
  (kern-obj-apply-damage obj "burning" 10))

;; kern-mk-terrain
;;      tag: variable name to reference terrain elsewhere in the script
;;     name: name presented to UI
;;    pmask: objective passablity mask (permitted bits set)
;;   sprite: animated image
;;    alpha: true if terrain blocks los
;;     cost: base movement cost (in action points)
;;    light: radiated light strength
;;   effect: optional procedure to run when an object is placed on the terrain,
;;           takes the object as it's sole argument

(kern-mk-terrain 't_lava            "lava"          2 s_lava            1 3  128 'burn)
(kern-mk-terrain 't_deep            "deep water"    4 s_deep            1 2  0 nil)
(kern-mk-terrain 't_shallow         "shallow water" 4 s_shallow         1 2  0 nil)
(kern-mk-terrain 't_shoals          "shoals"        8 s_shoals          1 2  0 nil)
(kern-mk-terrain 't_grass           "grass"         2 s_grass           1 2  0 nil)
(kern-mk-terrain 't_trees           "trees"         2 s_trees           1 2  0 nil)
(kern-mk-terrain 't_forest          "forest"        2 s_forest          0 4  0 nil)
(kern-mk-terrain 't_hills           "hills"         2 s_hills           1 3  0 nil)
(kern-mk-terrain 't_mountains       "mountains"     1 s_mountains       0 4  0 nil)
(kern-mk-terrain 't_leftwing        "castle wall"   1 s_leftwing        1 2  0 nil)
(kern-mk-terrain 't_rightwing       "castle wall"   1 s_rightwing       1 2  0 nil)
(kern-mk-terrain 't_cobblestone     "cobblestone"   2 s_cobblestone     1 2  0 nil)
(kern-mk-terrain 't_flagstones      "flagstones"    2 s_flagstone       1 2  0 nil)
(kern-mk-terrain 't_bog             "bog"           2 s_bog             1 3  0 nil)
(kern-mk-terrain 't_fire_terrain    "fire"          2 s_field_fire      1 2  512  'burn)
(kern-mk-terrain 't_fireplace       "fireplace"     2 s_fireplace       1 2  2048 'burn)
(kern-mk-terrain 't_bridge          "bridge"        14 s_bridge         1 2  0 nil)
(kern-mk-terrain 't_bridge_top      "bridge"        14 s_bridge_top     1 2  0 nil)
(kern-mk-terrain 't_bridge_bottom   "bridge"        14 s_bridge_bottom  1 2  0 nil)
(kern-mk-terrain 't_ship_hull       "ship's hull"   1 s_wall            1 0  0 nil)
(kern-mk-terrain 't_sh_hull_NE      "ship's hull"   1 s_wall_b          1 2  0 nil)
(kern-mk-terrain 't_sh_hull_NW      "ship's hull"   1 s_wall_a          1 2  0 nil)
(kern-mk-terrain 't_sh_hull_SE      "ship's hull"   1 s_wall_c          1 2  0 nil)
(kern-mk-terrain 't_sh_hull_SW      "ship's hull"   1 s_wall_d          1 2  0 nil)
(kern-mk-terrain 't_mast            "mast"          1 s_mast            1 2  0 nil)
(kern-mk-terrain 't_ships_wheel     "ship's wheel"  1 s_ships_wheel     1 2  0 nil)
(kern-mk-terrain 't_deck            "deck"          2 s_deck            1 2  0 nil)
(kern-mk-terrain 't_wall_rock       "rock wall"     1 s_wall_rock       0 2  0 nil)
(kern-mk-terrain 't_wall            "wall"          1 s_wall_stone      0 2  0 nil)
(kern-mk-terrain 't_wall_torch      "wall torch"    1 s_wall_torch      0 2  512 'burn)
(kern-mk-terrain 't_secret_door     "secret door"   2 s_secret_door     0 2  0 nil)
(kern-mk-terrain 't_sea_wall        "sea wall"      1 s_wall            0 2  0 nil)
(kern-mk-terrain 't_sea_wall_NE     "sea wall"      1 s_wall_b          0 2  0 nil)
(kern-mk-terrain 't_sea_wall_NW     "sea wall"      1 s_wall_a          0 2  0 nil)
(kern-mk-terrain 't_sea_wall_SE     "sea wall"      1 s_wall_c          0 2  0 nil)
(kern-mk-terrain 't_sea_wall_SW     "sea wall"      1 s_wall_d          0 2  0 nil)
(kern-mk-terrain 't_boulder         "boulder"       1 s_boulder         1 2  0 nil)
(kern-mk-terrain 't_ankh            "ankh"          1 s_ankh            1 2  0 nil)
(kern-mk-terrain 't_altar           "altar"         1 s_altar           1 2  0 nil)
(kern-mk-terrain 't_pillar          "pillar"        1 s_pillar          1 2  0 nil)
(kern-mk-terrain 't_counter_middle  "counter"       1 s_counter_middle  1 2  0 nil)
(kern-mk-terrain 't_counter_right   "counter"       1 s_counter_right   1 2  0 nil)
(kern-mk-terrain 't_counter_left    "counter"       1 s_counter_left    1 2  0 nil)
(kern-mk-terrain 't_counter_1x1     "counter"       1 s_counter_1x1     1 2  0 nil)
(kern-mk-terrain 't_trail_0         "trail"         2 s_trail_0         1 2  0 nil)
(kern-mk-terrain 't_trail_1         "trail"         2 s_trail_1         1 2  0 nil)
(kern-mk-terrain 't_trail_2         "trail"         2 s_trail_2         1 2  0 nil)
(kern-mk-terrain 't_trail_3         "trail"         2 s_trail_3         1 2  0 nil)
(kern-mk-terrain 't_trail_4         "trail"         2 s_trail_4         1 2  0 nil)
(kern-mk-terrain 't_trail_5         "trail"         2 s_trail_5         1 2  0 nil)
(kern-mk-terrain 't_trail_6         "trail"         2 s_trail_6         1 2  0 nil)
(kern-mk-terrain 't_trail_7         "trail"         2 s_trail_7         1 2  0 nil)
(kern-mk-terrain 't_trail_8         "trail"         2 s_trail_8         1 2  0 nil)
(kern-mk-terrain 't_trail_9         "trail"         2 s_trail_9         1 2  0 nil)
(kern-mk-terrain 't_trail_a         "trail"         2 s_trail_a         1 2  0 nil)
(kern-mk-terrain 't_trail_b         "trail"         2 s_trail_b         1 2  0 nil)
(kern-mk-terrain 't_trail_c         "trail"         2 s_trail_c         1 2  0 nil)
(kern-mk-terrain 't_trail_d         "trail"         2 s_trail_d         1 2  0 nil)
(kern-mk-terrain 't_trail_e         "trail"         2 s_trail_e         1 2  0 nil)
(kern-mk-terrain 't_trail_f         "trail"         2 s_trail_f         1 2  0 nil)
(kern-mk-terrain 't_A               "an A"          1 s_A               1 2  0 nil)
(kern-mk-terrain 't_B               "a B"           1 s_B               1 2  0 nil)
(kern-mk-terrain 't_C               "a C"           1 s_C               1 2  0 nil)
(kern-mk-terrain 't_D               "a D"           1 s_D               1 2  0 nil)
(kern-mk-terrain 't_E               "an E"          1 s_E               1 2  0 nil)
(kern-mk-terrain 't_F               "an F"          1 s_F               1 2  0 nil)
(kern-mk-terrain 't_G               "a G"           1 s_G               1 2  0 nil)
(kern-mk-terrain 't_H               "an H"          1 s_H               1 2  0 nil)
(kern-mk-terrain 't_I               "an I"          1 s_I               1 2  0 nil)
(kern-mk-terrain 't_J               "a J"           1 s_J               1 2  0 nil)
(kern-mk-terrain 't_K               "a K"           1 s_K               1 2  0 nil)
(kern-mk-terrain 't_L               "an L"          1 s_L               1 2  0 nil)
(kern-mk-terrain 't_M               "an M"          1 s_M               1 2  0 nil)
(kern-mk-terrain 't_N               "an N"          1 s_N               1 2  0 nil)
(kern-mk-terrain 't_O               "an O"          1 s_O               1 2  0 nil)
(kern-mk-terrain 't_P               "a P"           1 s_P               1 2  0 nil)
(kern-mk-terrain 't_Q               "a Q"           1 s_Q               1 2  0 nil)
(kern-mk-terrain 't_R               "an R"          1 s_R               1 2  0 nil)
(kern-mk-terrain 't_S               "an S"          1 s_S               1 2  0 nil)
(kern-mk-terrain 't_T               "a T"           1 s_T               1 2  0 nil)
(kern-mk-terrain 't_U               "a U"           1 s_U               1 2  0 nil)
(kern-mk-terrain 't_V               "a V"           1 s_V               1 2  0 nil)
(kern-mk-terrain 't_W               "a W"           1 s_W               1 2  0 nil)
(kern-mk-terrain 't_X               "an X"          1 s_X               1 2  0 nil)
(kern-mk-terrain 't_Y               "a Y"           1 s_Y               1 2  0 nil)
(kern-mk-terrain 't_Z               "a Z"           1 s_Z               1 2  0 nil)
(kern-mk-terrain 't_rune_A          "a rune"        1 s_rune_A          1 2  0 nil)
(kern-mk-terrain 't_rune_B          "a rune"        1 s_rune_B          1 2  0 nil)
(kern-mk-terrain 't_rune_C          "a rune"        1 s_rune_C          1 2  0 nil)
(kern-mk-terrain 't_rune_D          "a rune"        1 s_rune_D          1 2  0 nil)
(kern-mk-terrain 't_rune_E          "a rune"        1 s_rune_E          1 2  0 nil)
(kern-mk-terrain 't_rune_F          "a rune"        1 s_rune_F          1 2  0 nil)
(kern-mk-terrain 't_rune_G          "a rune"        1 s_rune_G          1 2  0 nil)
(kern-mk-terrain 't_rune_H          "a rune"        1 s_rune_H          1 2  0 nil)
(kern-mk-terrain 't_rune_I          "a rune"        1 s_rune_I          1 2  0 nil)
(kern-mk-terrain 't_rune_J          "a rune"        1 s_rune_J          1 2  0 nil)
(kern-mk-terrain 't_rune_K          "a rune"        1 s_rune_K          1 2  0 nil)
(kern-mk-terrain 't_rune_L          "a rune"        1 s_rune_L          1 2  0 nil)
(kern-mk-terrain 't_rune_M          "a rune"        1 s_rune_M          1 2  0 nil)
(kern-mk-terrain 't_rune_N          "a rune"        1 s_rune_N          1 2  0 nil)
(kern-mk-terrain 't_rune_O          "a rune"        1 s_rune_O          1 2  0 nil)
(kern-mk-terrain 't_rune_P          "a rune"        1 s_rune_P          1 2  0 nil)
(kern-mk-terrain 't_rune_Q          "a rune"        1 s_rune_Q          1 2  0 nil)
(kern-mk-terrain 't_rune_R          "a rune"        1 s_rune_R          1 2  0 nil)
(kern-mk-terrain 't_rune_S          "a rune"        1 s_rune_S          1 2  0 nil)
(kern-mk-terrain 't_rune_T          "a rune"        1 s_rune_T          1 2  0 nil)
(kern-mk-terrain 't_rune_U          "a rune"        1 s_rune_U          1 2  0 nil)
(kern-mk-terrain 't_rune_V          "a rune"        1 s_rune_V          1 2  0 nil)
(kern-mk-terrain 't_rune_W          "a rune"        1 s_rune_W          1 2  0 nil)
(kern-mk-terrain 't_rune_X          "a rune"        1 s_rune_X          1 2  0 nil)
(kern-mk-terrain 't_rune_Y          "a rune"        1 s_rune_Y          1 2  0 nil)
(kern-mk-terrain 't_rune_Z          "a rune"        1 s_rune_Z          1 2  0 nil)
(kern-mk-terrain 't_rune_TH         "a rune"        1 s_rune_TH         1 2  0 nil)
(kern-mk-terrain 't_rune_EE         "a rune"        1 s_rune_EE         1 2  0 nil)
(kern-mk-terrain 't_rune_NG         "a rune"        1 s_rune_NG         1 2  0 nil)
(kern-mk-terrain 't_rune_EA         "a rune"        1 s_rune_EA         1 2  0 nil)
(kern-mk-terrain 't_rune_ST         "a rune"        1 s_rune_ST         1 2  0 nil)
(kern-mk-terrain 't_rune_DOT        "a rune"        1 s_rune_DOTSEP     1 2  0 nil)
(kern-mk-terrain 't_red_roses       "roses"         2 s_trees_red       1 2  0 nil)
(kern-mk-terrain 't_arrow_slit      "arrow slit"    1 s_arrow_slit      1 2  0 nil)
(kern-mk-terrain 't_window_in_stone "window"        1 s_window_in_stone 1 2  0 nil)
