#!/bin/sh

#NAZGHUL=$HOME/nazghul-cvs
NAZGHUL=`pwd`
INSTALL=$HOME/nazghul-install
TMPDIR=$HOME/nazghul-tmp

version=$1
if [ -z "$version" ]; then
    echo "Usage:  $0 <release_version_number>"
    echo "    release_version_number should be something like x.y.z"
    exit 1
fi

rm -rf $INSTALL
cd $NAZGHUL
find . -name '*~' -exec rm -f {} \; 
./autogen.sh && \
make cvsclean && \
./autogen.sh && \
make alldist && \
mkdir -p $TMPDIR && \
cd $TMPDIR && \
rm -rf * && \
tar -xvzf $NAZGHUL/nazghul-$version.tar.gz && \
cd nazghul-$version &&     \
./configure --prefix=$INSTALL && \
make &&         \
make install && \
cd worlds/haxima-1.002 &&  \
$INSTALL/bin/nazghul

